modLoader="javafml"
loaderVersion="[43,)"
license="Academic Free License v3.0"

[[mods]]
modId="craft_kaisen"
version="1.0.0"
displayName="Craft Kaisen"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="tobia, MCreator"

[[dependencies.craft_kaisen]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"


[[dependencies.craft_kaisen]]
    modId="kleiders_custom_renderer"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.craft_kaisen]]
    modId="kleidersplayerrenderer"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.craft_kaisen]]
    modId="kleiders_custom_renderer"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.craft_kaisen]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.craft_kaisen]]
    modId="playeranimator"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

